# Generated by Django 4.2.6 on 2023-11-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovie',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
